### ISSUE TITLE
Fatal error: Uncaught CoinGate\BadRequest: AuthTokenMissing in /home/nbknkiy0hjz9/public_html/hedgecash/coingate-php/lib/Exception.php:

### ISSUE THREAD

**Issue by dammak13** [coingate/coingate-php#12]
Hello.

I'm facing below error while just running the create_order API.

Fatal error: Uncaught CoinGate\BadRequest: AuthTokenMissing in /home/nbknkiy0hjz9/public_html/hedgecash/coingate-php/lib/Exception.php:34 Stack trace: #0 /home/nbknkiy0hjz9/public_html/hedgecash/coingate-php/lib/CoinGate.php(49): CoinGate\Exception::throwException(400, Array) #1 /home/nbknkiy0hjz9/public_html/hedgecash/coingate-php/lib/Merchant/Order.php(55): CoinGate\CoinGate::request('/orders', 'POST', Array, Array) #2 /home/nbknkiy0hjz9/public_html/hedgecash/coingate-php/lib/Merchant/Order.php(47): CoinGate\Merchant\Order::createOrFail(Array, Array, Array) #3 /home/nbknkiy0hjz9/public_html/hedgecash/index.php(35): CoinGate\Merchant\Order::create(Array) #4 {main} thrown in /home/nbknkiy0hjz9/public_html/hedgecash/coingate-php/lib/Exception.php on line 34

================================================

<?php
require_once('coingate-php/init.php');

$testConnection = \CoinGate\CoinGate::testConnection(array(
  'environment'   => 'sandbox',
  'auth_token'    => '-s5BB7bo6u93kG3CWhydW4GMxvsHWxjhKiLfRNEh'
));

if ($testConnection !== true) {
  echo $testConnection; // CoinGate\BadCredentials: BadCredentials Not found App by Access-Key
}
else{
	echo $testConnection;
	
}

//use CoinGate\CoinGate;
$post_params = array(
                   'order_id'          => 'YOUR-CUSTOM-ORDER-ID-115',
                   'price_amount'      => 1050.99,
                   'price_currency'    => 'USD',
                   'receive_currency'  => 'USD',
                   'callback_url'      => 'http://localhost/hedgecash/index.php/callback?token=6tCENGUYI62ojkuzDPX7Jg',
                   'cancel_url'        => 'http://localhost/hedgecash/index.php',
                   'success_url'       => 'http://localhost/hedgecash/index.php',
                   'title'             => 'Order #112',
                   'description'       => 'Apple Iphone 6',
				   'auth_token' 	   => '-s5BB7bo6u93kG3CWhydW4GMxvsHWxjhKiLfRNEh'
               );

			   echo 'I am here.';
$order = \CoinGate\Merchant\Order::create($post_params);

if ($order) {
    echo $order->status;
    
    print_r($order);
} else {
    # Order Is Not Valid
	print_r($order);
}

?>

====================================

**Comment by nezaboravi** [comment]
Same here
