### ISSUE TITLE
Sandbox authentication in Javascript

### ISSUE THREAD

**Issue by ghost** [coingate/coingate-php#2]
Hi, I would like to use Coingate to receive payments but how can I authenticate my credentials using javascript?

**Comment by minvs1** [comment]
Hello.

We currently don't have any examples in JavaScript. However you should not use API in front-end, by doing that you expose your API Secret to users, although it is possible.

You may freely use our API in NodeJS application. Just please use our [API documentation](https://developer.coingate.com/docs/getting-started) and [Examples](https://developer.coingate.com/docs/code-examples).

**Comment by ghost** [comment]
I am getting a 401 with javascript I dont know why? it seems my credentials are bad but I dont see the problem

`let appId = '485'
let apiKey = 'u45wEKPvnrORIaydflHxbF'
let apiSecret = 'CEmlwgoqvMViH9KaYyObzGhZUtWB4cP8'
let uri = 'https://api-sandbox.coingate.com/v1/orders'


let fecha = dateFns.format(new Date())
let nonce = dateFns.getTime(fecha)
let message = nonce + appId + apiKey
console.log(message);
let signature = sha256.hmac(apiSecret, message);
console.log(signature);


let formData = new FormData()
formData.append('order_id', 'CGORDER-12345')
formData.append('price', '1050.99')
formData.append('currency', 'VEF')
formData.append('receive_currency', 'VEF')
formData.append('title', 'Apple Iphone 6')
formData.append('description', '1 x Apple Iphone 6, 1 x Apple MacBook Air')
formData.append('callback_url', 'http://example.com/payments/callback?token=tDBujwMWVM9bfV8t1vkzLw')
formData.append('cancel_url', 'http://example.com/cart')
formData.append('success_url', 'http://example.com/account/orders')

let httpHeaders = {
    'Access-Nonce': nonce,
    'Access-Key': apiKey,
    'Access-Signature': signature,
    'Content-Type': 'application/x-www-form-urlencoded'
}
let headers = new Headers(httpHeaders)

let init = {
    method: 'POST',
    headers: headers,
    body: formData,
    mode: 'no-cors'
}

let request = new Request(uri, init)

fetch(request)
    .then((res) => {
        console.log(res);

    })`

**Comment by Kamikozz** [comment]
> 

Sorry, is there way to send requests from frontend (js)? I'm just getting CORS error for all of my requests (even `/ping` or `/currencies`)
