### ISSUE TITLE
Handle 5xx response codes

### ISSUE THREAD

**Issue by FallDi** [coingate/coingate-php#6]
Steps to reproduce:
1) CoinGate respond with 504 HTTP code.

Actual result:
`APIError` exception spawned

Expected result:
`InternalServerError` exception spawned

Root cause: https://github.com/coingate/coingate-php/blob/master/lib/Exception.php#L53

I suggest throw `InternalServerError` on any 5XX error, because now `InternalServerError` is useless

**Comment by ibaciulis** [comment]
Hi FallDi,

we added 504 to InternalServerError exception in 3.0.1 version.

**Comment by FallDi** [comment]
Hi @ibaciulis,
Well done! Thank you very much
