### ISSUE TITLE
How we can use Alt-coins

### ISSUE THREAD

**Issue by alishannb** [coingate/coingate-php#9]
Hi,

Can you please describe how we can use alt-coins by using PHP? I have integrated and using this (coingate) library. But it is not allowing me to use other alt-coins. I also have attached the image to this issue. Please have a look at the attached image for more clarity. 

Best Regards,

![screenshot_14](https://user-images.githubusercontent.com/36223819/41244386-56244c6e-6dbe-11e8-833b-03f46654a3a6.png)

**Comment by arnasfomenko** [comment]
Hello,

I think you are using API V1 instead of API V2 that is why you cannot change to any other cryptocurrency.

Can you please share the code with me? I will help you to make it work with API v2.

Otherwise, please follow : https://developer.coingate.com

Best regards,
Arnas

**Comment by alishannb** [comment]
Hi @arnasfomenko,

Thank you for pointing out the issue. I was using V1. I just shifted to V2 and now I am able to use altcoins.

**Comment by arnasfomenko** [comment]
Hello @alishannb,

Glad you figured it out.

Best regards,
CoinGate Team
